#!/usr/bin/env python3
"""Emit the RSPRecomp config for Pokemon Stadium 2's own audio microcode.

The runtime was running Stadium 1's recompiled aspMain, whose bytes do not
appear anywhere in the Stadium 2 ROM. Stadium 2's own audio ucode is at ROM
0x1060 (task ucode vaddr 0x80000460), 0x1000 bytes, with ucode_data at ROM
0x87AF0.

The microcode is linked for IMEM 0x000, i.e. it fills IMEM by itself and no
rspboot stays resident under it. That is the whole config: text_address
0x04001000 with the ROM image at text_offset 0x1060 and text_size 0x1000.

Do NOT prepend the rspboot at ROM 0xB70. That blob DMAs the ucode to IMEM 0x080
and enters it there, and a blob built that way is off by 0x80 everywhere -- it
was the cause of two failed attempts. Whatever ucode_boot the audio task
actually passes, it is not that one, and it does not matter here: librecomp's
run_task already does the boot's work (ucode_data into DMEM[0], the OSTask at
DMEM[0xFC0]) before calling the recompiled ucode.

Three independent checks pin the base at 0x000; each one lands on a delay slot
or mid-loop if the base is 0x080 instead:

    IMEM 0x0AC  j 0x060    -> 0x060 `lw $26,0($29)`, head of the command
                              dispatch loop (the ucode's main loop-back)
    IMEM 0x058  jal 0x0CC  -> 0x0CC `addi $5,$31,0`, a subroutine saving ra
    ucode_data  0x1154     -> 0x154 `andi $3,$25,0xFFFF`, a handler head
"""
import argparse
import struct
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

parser = argparse.ArgumentParser(description="Build Stadium 2's audio microcode config from a local ROM.")
parser.add_argument("--rom", type=Path, default=REPO_ROOT / "baserom.z64")
parser.add_argument("--output", type=Path, default=REPO_ROOT / "aspMain.ps2.us.toml")
args = parser.parse_args()
ROM = args.rom
OUT_TOML = args.output

ASPMAIN_ROM, ASPMAIN_SIZE = 0x001060, 0x1000
UCODE_DATA_ROM = 0x087AF0

rom = ROM.read_bytes()
assert struct.unpack_from(">I", rom, ASPMAIN_ROM)[0] == 0x340A0FC0, \
    "ucode entry is not `ori $10, $zero, 0xFC0`"

# Audio-command handler PCs: halfwords at ucode_data +0x10..+0x3E. +0x00..+0x0E
# is a constants block and +0x40 onward are bit masks.
targets = []
for off in range(0x10, 0x40, 2):
    pc = struct.unpack_from(">H", rom, UCODE_DATA_ROM + off)[0]
    assert 0x1000 <= pc < 0x1000 + ASPMAIN_SIZE, "handler PC 0x%04X out of IMEM range" % pc
    if pc not in targets:
        targets.append(pc)
print("dispatch handlers: %d unique PCs" % len(targets))

lines = ["    " + " ".join("0x%04X," % t for t in targets[i:i + 8])
         for i in range(0, len(targets), 8)]

toml = '''# Pokemon Stadium 2 (US) audio microcode.
#
# Stadium 2 does NOT ship Stadium 1's aspMain: none of Stadium 1's ucode bytes
# occur in this ROM, and the DMEM dispatch header differs entirely. Running
# Stadium 1's recompiled aspMain against Stadium 2 command lists made its
# handlers compute RDRAM addresses from the wrong ABI and corrupt unrelated
# memory, so M_AUDTASK was temporarily routed to a no-op. This is the real
# thing, recompiled from this ROM.
#
# Generated by tools/build_ps2_aspmain.py -- read it before editing these
# numbers. In particular: this ucode is linked for IMEM 0x000 and no rspboot
# belongs in front of it. Prepending the rspboot at ROM 0xB70 (which loads to
# IMEM 0x080) shifts every absolute J/JAL and every dispatch-table PC by 0x80
# and hangs the task; that mistake cost two on-device attempts.
text_offset = 0x1060
text_size = 0x1000
text_address = 0x04001000
rom_file_path = "baserom.z64"
output_file_path = "rsp/aspMain_ps2.cpp"
output_function_name = "aspMain_ps2"

# Handler PCs read from ucode_data (ROM 0x87AF0) halfwords +0x10..+0x3E. The
# dispatch loop reaches them with `jr`, so static analysis cannot see them and
# they must be declared or every handler call is an "Unhandled jump target".
extra_indirect_branch_targets = [
%s
]
''' % "\n".join(lines)

OUT_TOML.parent.mkdir(parents=True, exist_ok=True)
OUT_TOML.write_text(toml)
print("wrote %s" % OUT_TOML)
