#!/usr/bin/env python3
"""Derive N64Recomp metadata from the Pokemon Stadium 2 ELF."""

import argparse
import re
import subprocess
from collections import defaultdict
from pathlib import Path


SECTION_RE = re.compile(r"\[\s*(\d+)\]\s+(\.fragment\d+)\s+PROGBITS")


def run(readelf: str, *args: str, elf: Path) -> str:
    return subprocess.run(
        [readelf, *args, str(elf)],
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def parse_symbols(text: str):
    for line in text.splitlines():
        parts = line.split()
        if len(parts) < 8 or not parts[0].endswith(":"):
            continue
        try:
            address = int(parts[1], 16)
            size = int(parts[2])
        except ValueError:
            continue
        yield address, size, parts[3], parts[6], parts[7]


def derive_sizes(symbols):
    by_section = defaultdict(list)
    for symbol in symbols:
        address, _, _, section, _ = symbol
        if address and section not in {"ABS", "UND", "COM"}:
            by_section[section].append(symbol)

    derived = []
    for section_symbols in by_section.values():
        boundaries = sorted({symbol[0] for symbol in section_symbols})
        for address, size, symbol_type, _, name in section_symbols:
            if symbol_type != "FUNC" or size or name.startswith((".L", "D_")):
                continue
            next_address = next((value for value in boundaries if value > address), None)
            if next_address is None:
                continue
            derived_size = next_address - address
            if 0 < derived_size <= 0x10000 and derived_size % 4 == 0:
                derived.append((address, name, derived_size))
    return sorted(set(derived))


def main() -> None:
    parser = argparse.ArgumentParser()
    repo_root = Path(__file__).resolve().parents[1]
    workspace_root = repo_root.parents[1]
    default_elf = workspace_root / "decomp" / "pokestadiumgs" / "build" / "pokestadiumgs-us.elf"
    parser.add_argument("--elf", type=Path, default=default_elf)
    parser.add_argument("--readelf", default="mips-linux-gnu-readelf")
    parser.add_argument("--fragments-out", type=Path, default=Path("fragments_relocatable.txt"))
    parser.add_argument("--sizes-out", type=Path, default=Path("function_sizes.toml"))
    args = parser.parse_args()

    sections = run(args.readelf, "-S", "-W", elf=args.elf)
    fragments = sorted(
        {match.group(2) for match in SECTION_RE.finditer(sections)},
        key=lambda value: int(value.removeprefix(".fragment")),
    )
    args.fragments_out.write_text("\n".join(fragments) + "\n", encoding="utf-8")

    symbols = parse_symbols(run(args.readelf, "-s", "-W", elf=args.elf))
    sizes = derive_sizes(symbols)
    lines = [
        "# Generated by tools/derive_recomp_metadata.py; do not edit.",
        f"# Derived sizes for {len(sizes)} zero-size FUNC symbols.",
        "",
    ]
    for address, name, size in sizes:
        lines.extend(
            [
                "[[input.function_sizes]]",
                f'name = "{name}"',
                f"size = 0x{size:X} # vram 0x{address:08X}",
                "",
            ]
        )
    args.sizes_out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(fragments)} fragments and {len(sizes)} function sizes")


if __name__ == "__main__":
    main()
